// Code generated by native-context-gen; DO NOT EDIT.

export const nativeCardCatalog = {
  "$schema": "./native-card-catalog.schema.json",
  "version": 1,
  "limits": {
    "maxDepth": 32,
    "maxNodes": 500,
    "maxChildrenPerNode": 200,
    "maxActionsPerEvent": 64,
    "maxExpressionDepth": 32,
    "maxDataDepth": 32,
    "maxDataNodes": 500,
    "maxContainerItems": 200,
    "maxContentBytes": 2097152
  },
  "components": {
    "Container": {
      "allowedProps": {
        "padding": {
          "type": "number",
          "minimum": 0
        }
      },
      "requiredProps": [],
      "allowedEvents": []
    },
    "Row": {
      "allowedProps": {
        "spacing": {
          "type": "number",
          "minimum": 0
        }
      },
      "requiredProps": [],
      "allowedEvents": []
    },
    "Column": {
      "allowedProps": {
        "spacing": {
          "type": "number",
          "minimum": 0
        }
      },
      "requiredProps": [],
      "allowedEvents": []
    },
    "Stack": {
      "allowedProps": {},
      "requiredProps": [],
      "allowedEvents": []
    },
    "Grid": {
      "allowedProps": {
        "columns": {
          "type": "integer",
          "minimum": 1,
          "maximum": 6
        },
        "spacing": {
          "type": "number",
          "minimum": 0
        }
      },
      "requiredProps": [],
      "allowedEvents": []
    },
    "Scroll": {
      "allowedProps": {},
      "requiredProps": [],
      "allowedEvents": []
    },
    "Divider": {
      "allowedProps": {},
      "requiredProps": [],
      "allowedEvents": []
    },
    "Text": {
      "allowedProps": {
        "text": {
          "type": "string",
          "binding": true
        },
        "style": {
          "type": "string",
          "enum": [
            "body",
            "title",
            "display"
          ]
        }
      },
      "requiredProps": [],
      "allowedEvents": []
    },
    "Icon": {
      "allowedProps": {
        "name": {
          "type": "string",
          "enum": [
            "widgets",
            "timer",
            "check",
            "warning",
            "settings"
          ]
        }
      },
      "requiredProps": [],
      "allowedEvents": []
    },
    "Image": {
      "allowedProps": {
        "alt": {
          "type": "string"
        }
      },
      "requiredProps": [],
      "allowedEvents": []
    },
    "Badge": {
      "allowedProps": {
        "label": {
          "type": "string",
          "binding": true
        }
      },
      "requiredProps": [],
      "allowedEvents": []
    },
    "Progress": {
      "allowedProps": {
        "value": {
          "type": "number",
          "binding": true
        }
      },
      "requiredProps": [],
      "allowedEvents": []
    },
    "Chart": {
      "allowedProps": {
        "values": {
          "type": "numberList",
          "binding": true
        }
      },
      "requiredProps": [],
      "allowedEvents": []
    },
    "Button": {
      "allowedProps": {
        "label": {
          "type": "string",
          "binding": true
        }
      },
      "requiredProps": [],
      "allowedEvents": [
        "onPressed"
      ]
    },
    "TextInput": {
      "allowedProps": {
        "label": {
          "type": "string"
        },
        "valuePath": {
          "type": "string",
          "minLength": 1,
          "pattern": "^[^.]+(\\.[^.]+)*$"
        }
      },
      "requiredProps": [
        "valuePath"
      ],
      "allowedEvents": []
    },
    "Checkbox": {
      "allowedProps": {
        "label": {
          "type": "string"
        },
        "valuePath": {
          "type": "string",
          "minLength": 1,
          "pattern": "^[^.]+(\\.[^.]+)*$"
        }
      },
      "requiredProps": [
        "valuePath"
      ],
      "allowedEvents": []
    },
    "Select": {
      "allowedProps": {
        "label": {
          "type": "string"
        },
        "valuePath": {
          "type": "string",
          "minLength": 1,
          "pattern": "^[^.]+(\\.[^.]+)*$"
        },
        "options": {
          "type": "stringList",
          "uniqueItems": true
        }
      },
      "requiredProps": [
        "valuePath"
      ],
      "allowedEvents": []
    },
    "Slider": {
      "allowedProps": {
        "valuePath": {
          "type": "string",
          "minLength": 1,
          "pattern": "^[^.]+(\\.[^.]+)*$"
        },
        "min": {
          "type": "number"
        },
        "max": {
          "type": "number"
        }
      },
      "requiredProps": [
        "valuePath"
      ],
      "allowedEvents": []
    },
    "List": {
      "allowedProps": {},
      "requiredProps": [],
      "allowedEvents": []
    },
    "KeyValue": {
      "allowedProps": {
        "label": {
          "type": "string",
          "binding": true
        },
        "value": {
          "type": "any",
          "binding": true
        }
      },
      "requiredProps": [],
      "allowedEvents": []
    },
    "EmptyState": {
      "allowedProps": {
        "title": {
          "type": "string"
        }
      },
      "requiredProps": [],
      "allowedEvents": []
    },
    "ErrorState": {
      "allowedProps": {
        "message": {
          "type": "string"
        }
      },
      "requiredProps": [],
      "allowedEvents": []
    }
  },
  "actions": {
    "set": {
      "requiredFields": [
        "path",
        "value"
      ],
      "optionalFields": [],
      "valueRule": {
        "type": "any",
        "binding": true
      }
    },
    "increment": {
      "requiredFields": [
        "path"
      ],
      "optionalFields": [
        "value"
      ],
      "valueRule": {
        "type": "number",
        "binding": true
      }
    },
    "toggle": {
      "requiredFields": [
        "path"
      ],
      "optionalFields": []
    },
    "append": {
      "requiredFields": [
        "path",
        "value"
      ],
      "optionalFields": [],
      "valueRule": {
        "type": "any",
        "binding": true
      }
    },
    "remove": {
      "requiredFields": [
        "path",
        "value"
      ],
      "optionalFields": [],
      "valueRule": {
        "type": "any",
        "binding": true
      }
    },
    "startTimer": {
      "requiredFields": [
        "path",
        "value"
      ],
      "optionalFields": [],
      "valueRule": {
        "type": "timerConfiguration"
      }
    },
    "stopTimer": {
      "requiredFields": [
        "path"
      ],
      "optionalFields": []
    },
    "capability.invoke": {
      "requiredFields": [
        "method"
      ],
      "optionalFields": [
        "path",
        "params"
      ]
    }
  },
  "expressions": {
    "add": {
      "minArgs": 1,
      "argumentType": "number",
      "resultType": "number"
    },
    "subtract": {
      "minArgs": 2,
      "maxArgs": 2,
      "argumentType": "number",
      "resultType": "number"
    },
    "multiply": {
      "minArgs": 1,
      "argumentType": "number",
      "resultType": "number"
    },
    "divide": {
      "minArgs": 2,
      "maxArgs": 2,
      "argumentType": "number",
      "resultType": "number",
      "constraint": "nonZeroDivisor"
    },
    "eq": {
      "minArgs": 2,
      "maxArgs": 2,
      "argumentType": "any",
      "resultType": "boolean"
    },
    "gt": {
      "minArgs": 2,
      "maxArgs": 2,
      "argumentType": "number",
      "resultType": "boolean"
    },
    "gte": {
      "minArgs": 2,
      "maxArgs": 2,
      "argumentType": "number",
      "resultType": "boolean"
    },
    "lt": {
      "minArgs": 2,
      "maxArgs": 2,
      "argumentType": "number",
      "resultType": "boolean"
    },
    "lte": {
      "minArgs": 2,
      "maxArgs": 2,
      "argumentType": "number",
      "resultType": "boolean"
    },
    "and": {
      "minArgs": 1,
      "argumentType": "boolean",
      "resultType": "boolean"
    },
    "or": {
      "minArgs": 1,
      "argumentType": "boolean",
      "resultType": "boolean"
    },
    "not": {
      "minArgs": 1,
      "maxArgs": 1,
      "argumentType": "boolean",
      "resultType": "boolean"
    },
    "concat": {
      "minArgs": 0,
      "argumentType": "any",
      "resultType": "string"
    },
    "formatDuration": {
      "minArgs": 1,
      "maxArgs": 1,
      "argumentType": "number",
      "resultType": "string",
      "constraint": "nonNegative"
    }
  },
  "capabilityMethods": {
    "runtime.getContext": {
      "manifestCapability": null,
      "nativeSupported": false,
      "unsupportedReason": "NativeCard has no runtime.getContext broker handler"
    },
    "storage.get": {
      "manifestCapability": "storage",
      "nativeSupported": false,
      "unsupportedReason": "NativeCard has no storage broker handler"
    },
    "storage.set": {
      "manifestCapability": "storage",
      "nativeSupported": false,
      "unsupportedReason": "NativeCard has no storage broker handler"
    },
    "storage.delete": {
      "manifestCapability": "storage",
      "nativeSupported": false,
      "unsupportedReason": "NativeCard has no storage broker handler"
    },
    "storage.list": {
      "manifestCapability": "storage",
      "nativeSupported": false,
      "unsupportedReason": "NativeCard has no storage broker handler"
    },
    "notification.show": {
      "manifestCapability": "notification.show",
      "nativeSupported": true
    },
    "clipboard.write": {
      "manifestCapability": "clipboard.write",
      "nativeSupported": true
    },
    "clipboard.read": {
      "manifestCapability": "clipboard.read",
      "nativeSupported": true
    },
    "host.openExternal": {
      "manifestCapability": "host.openExternal",
      "nativeSupported": true
    },
    "network.fetch": {
      "manifestCapability": "network.fetch",
      "nativeSupported": true
    },
    "system.metrics.get": {
      "manifestCapability": "system.metrics.read",
      "nativeSupported": true
    },
    "system.metrics.subscribe": {
      "manifestCapability": "system.metrics.read",
      "nativeSupported": false,
      "unsupportedReason": "NativeCard has no metrics subscription broker handler"
    },
    "system.metrics.unsubscribe": {
      "manifestCapability": "system.metrics.read",
      "nativeSupported": false,
      "unsupportedReason": "NativeCard has no metrics subscription broker handler"
    },
    "window.getState": {
      "manifestCapability": "window.manageSelf",
      "nativeSupported": true
    },
    "window.detach": {
      "manifestCapability": "window.manageSelf",
      "nativeSupported": true
    },
    "window.dock": {
      "manifestCapability": "window.manageSelf",
      "nativeSupported": true
    },
    "window.setAlwaysOnTop": {
      "manifestCapability": "window.manageSelf",
      "nativeSupported": true
    },
    "window.requestAttention": {
      "manifestCapability": "window.manageSelf",
      "nativeSupported": true
    }
  },
  "unsupported": {
    "conditionalVisibility": "Flutter NativeCard renderer does not implement conditional node visibility",
    "dynamicListMapping": "Flutter List renders only declared child nodes and does not map state collections",
    "dateFormatting": "Flutter expression evaluator implements formatDuration only, not date formatting"
  }
} as const;
