package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"sort"
	"strconv"
	"strings"
)

func buildDartCatalog(catalog catalogDocument) ([]byte, error) {
	var source strings.Builder
	source.WriteString("// Code generated by native-context-gen; DO NOT EDIT.\n\n")
	fmt.Fprintf(&source, "const nativeCatalogMaxActionsPerEvent = %d;\n\n", catalog.Limits["maxActionsPerEvent"])
	writeDartSetMap(&source, "nativeCatalogComponentProps", sortedKeys(catalog.Components), func(name string) []string {
		return sortedKeys(catalog.Components[name].AllowedProps)
	})
	writeDartSetMap(&source, "nativeCatalogComponentRequiredProps", sortedKeys(catalog.Components), func(name string) []string {
		return catalog.Components[name].RequiredProps
	})
	writeDartSetMap(&source, "nativeCatalogComponentEvents", sortedKeys(catalog.Components), func(name string) []string {
		return catalog.Components[name].AllowedEvents
	})
	writeDartSetMap(&source, "nativeCatalogActionRequiredFields", sortedKeys(catalog.Actions), func(name string) []string {
		return catalog.Actions[name].RequiredFields
	})
	writeDartSetMap(&source, "nativeCatalogActionOptionalFields", sortedKeys(catalog.Actions), func(name string) []string {
		return catalog.Actions[name].OptionalFields
	})
	source.WriteString("const nativeCatalogExpressionArity = <String, ({int min, int? max})>{\n")
	for _, name := range sortedKeys(catalog.Expressions) {
		rule := catalog.Expressions[name]
		maxValue := "null"
		if rule.MaxArgs != nil {
			maxValue = strconv.Itoa(*rule.MaxArgs)
		}
		fmt.Fprintf(&source, "  %s: (min: %d, max: %s),\n", dartString(name), rule.MinArgs, maxValue)
	}
	source.WriteString("};\n")
	return []byte(source.String()), nil
}

func writeDartSetMap(source *strings.Builder, name string, keys []string, values func(string) []string) {
	fmt.Fprintf(source, "const %s = <String, Set<String>>{\n", name)
	for _, key := range keys {
		items := append([]string(nil), values(key)...)
		sort.Strings(items)
		fmt.Fprintf(source, "  %s: <String>{", dartString(key))
		for index, item := range items {
			if index > 0 {
				source.WriteString(", ")
			}
			source.WriteString(dartString(item))
		}
		source.WriteString("},\n")
	}
	source.WriteString("};\n\n")
}

func dartString(value string) string {
	replacer := strings.NewReplacer(
		`\`, `\\`,
		`'`, `\'`,
		`$`, `\$`,
		"\n", `\n`,
		"\r", `\r`,
	)
	return "'" + replacer.Replace(value) + "'"
}

func buildTypeScriptCatalog(catalogJSON []byte) ([]byte, error) {
	var pretty bytes.Buffer
	if err := json.Indent(&pretty, catalogJSON, "", "  "); err != nil {
		return nil, fmt.Errorf("format generated TypeScript catalog: %w", err)
	}
	return []byte("// Code generated by native-context-gen; DO NOT EDIT.\n\nexport const nativeCardCatalog = " + pretty.String() + " as const;\n"), nil
}
