package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"

	"github.com/santhosh-tekuri/jsonschema/v6"
)

const generatedHeader = "// Code generated by native-context-gen; DO NOT EDIT.\n"

type catalogDocument struct {
	Version           int                             `json:"version"`
	Limits            map[string]int                  `json:"limits"`
	Components        map[string]componentRule        `json:"components"`
	Actions           map[string]actionRule           `json:"actions"`
	Expressions       map[string]expressionRule       `json:"expressions"`
	CapabilityMethods map[string]capabilityMethodRule `json:"capabilityMethods"`
	Unsupported       map[string]string               `json:"unsupported"`
}

type componentRule struct {
	AllowedProps  map[string]valueRule `json:"allowedProps"`
	RequiredProps []string             `json:"requiredProps"`
	AllowedEvents []string             `json:"allowedEvents"`
}

type actionRule struct {
	RequiredFields []string   `json:"requiredFields"`
	OptionalFields []string   `json:"optionalFields"`
	ValueRule      *valueRule `json:"valueRule"`
}

type valueRule struct {
	Type        string   `json:"type"`
	Binding     bool     `json:"binding"`
	Enum        []string `json:"enum"`
	Minimum     *float64 `json:"minimum"`
	Maximum     *float64 `json:"maximum"`
	MinLength   *int     `json:"minLength"`
	Pattern     string   `json:"pattern"`
	UniqueItems bool     `json:"uniqueItems"`
}

type expressionRule struct {
	MinArgs      int    `json:"minArgs"`
	MaxArgs      *int   `json:"maxArgs"`
	ArgumentType string `json:"argumentType"`
	ResultType   string `json:"resultType"`
	Constraint   string `json:"constraint"`
}

type capabilityMethodRule struct {
	ManifestCapability *string `json:"manifestCapability"`
	NativeSupported    bool    `json:"nativeSupported"`
	UnsupportedReason  string  `json:"unsupportedReason"`
}

type localRPCDocument struct {
	ContractVersion int      `json:"contractVersion"`
	Methods         []string `json:"methods"`
}

func main() {
	check := flag.Bool("check", false, "fail when generated output is stale")
	rootFlag := flag.String("root", "", "repository root (auto-detected by default)")
	outputFlag := flag.String("output", "", "generated Go output path")
	schemaOutputFlag := flag.String("schema-output", "", "generated NativeCard schema output path")
	dartOutputFlag := flag.String("dart-output", "", "generated Dart catalog output path")
	typeScriptOutputFlag := flag.String("typescript-output", "", "generated TypeScript catalog output path")
	flag.Parse()

	root, err := resolveRoot(*rootFlag)
	if err != nil {
		fatal(err)
	}
	output := *outputFlag
	if output == "" {
		output = filepath.Join(root, "services", "cloud", "internal", "agent", "native_contract_context_generated.go")
	}
	schemaOutput := *schemaOutputFlag
	if schemaOutput == "" {
		schemaOutput = filepath.Join(root, "contracts", "card", "native-card.schema.json")
	}
	dartOutput := *dartOutputFlag
	if dartOutput == "" {
		dartOutput = filepath.Join(root, "apps", "desktop", "lib", "src", "native_card", "native_card_catalog_generated.dart")
	}
	typeScriptOutput := *typeScriptOutputFlag
	if typeScriptOutput == "" {
		typeScriptOutput = filepath.Join(root, "contracts", "typescript", "native-card-catalog.generated.ts")
	}
	expected, err := generate(root)
	if err != nil {
		fatal(err)
	}
	if *check {
		actual, readErr := os.ReadFile(output)
		if readErr != nil || !bytes.Equal(actual, expected.GoContext) {
			fatal(fmt.Errorf("generated NativeCard context is out of date: run go run ./cmd/native-context-gen"))
		}
		actualSchema, readErr := os.ReadFile(schemaOutput)
		if readErr != nil || !bytes.Equal(actualSchema, expected.NativeSchema) {
			fatal(fmt.Errorf("generated NativeCard schema is out of date: run go run ./cmd/native-context-gen"))
		}
		actualDart, readErr := os.ReadFile(dartOutput)
		if readErr != nil || !bytes.Equal(actualDart, expected.DartCatalog) {
			fatal(fmt.Errorf("generated Dart NativeCard catalog is out of date: run go run ./cmd/native-context-gen"))
		}
		actualTypeScript, readErr := os.ReadFile(typeScriptOutput)
		if readErr != nil || !bytes.Equal(actualTypeScript, expected.TypeScriptCatalog) {
			fatal(fmt.Errorf("generated TypeScript NativeCard catalog is out of date: run go run ./cmd/native-context-gen"))
		}
		return
	}
	if err := os.WriteFile(schemaOutput, expected.NativeSchema, 0o644); err != nil {
		fatal(fmt.Errorf("write generated NativeCard schema: %w", err))
	}
	if err := os.WriteFile(dartOutput, expected.DartCatalog, 0o644); err != nil {
		fatal(fmt.Errorf("write generated Dart NativeCard catalog: %w", err))
	}
	if err := os.WriteFile(typeScriptOutput, expected.TypeScriptCatalog, 0o644); err != nil {
		fatal(fmt.Errorf("write generated TypeScript NativeCard catalog: %w", err))
	}
	if err := os.WriteFile(output, expected.GoContext, 0o644); err != nil {
		fatal(fmt.Errorf("write generated context: %w", err))
	}
}

func resolveRoot(explicit string) (string, error) {
	if explicit != "" {
		root, err := filepath.Abs(explicit)
		if err != nil {
			return "", fmt.Errorf("resolve repository root: %w", err)
		}
		return root, nil
	}
	current, err := os.Getwd()
	if err != nil {
		return "", fmt.Errorf("get working directory: %w", err)
	}
	for {
		if _, err := os.Stat(filepath.Join(current, "contracts", "card", "native-card-catalog.v1.json")); err == nil {
			return current, nil
		}
		parent := filepath.Dir(current)
		if parent == current {
			return "", fmt.Errorf("repository root not found from %s", current)
		}
		current = parent
	}
}

type generatedArtifacts struct {
	GoContext         []byte
	NativeSchema      []byte
	DartCatalog       []byte
	TypeScriptCatalog []byte
}

func generate(root string) (generatedArtifacts, error) {
	catalogSchema, err := compactFile(filepath.Join(root, "contracts", "card", "native-card-catalog.schema.json"))
	if err != nil {
		return generatedArtifacts{}, err
	}
	catalog, err := compactFile(filepath.Join(root, "contracts", "card", "native-card-catalog.v1.json"))
	if err != nil {
		return generatedArtifacts{}, err
	}
	if err := validateCatalogDocument(catalogSchema, catalog); err != nil {
		return generatedArtifacts{}, err
	}
	var catalogDocument catalogDocument
	if err := json.Unmarshal(catalog, &catalogDocument); err != nil {
		return generatedArtifacts{}, fmt.Errorf("decode NativeCard catalog: %w", err)
	}
	schema, err := buildNativeSchema(catalogDocument)
	if err != nil {
		return generatedArtifacts{}, err
	}
	dartCatalog, err := buildDartCatalog(catalogDocument)
	if err != nil {
		return generatedArtifacts{}, err
	}
	typeScriptCatalog, err := buildTypeScriptCatalog(catalog)
	if err != nil {
		return generatedArtifacts{}, err
	}
	localRPC, err := compactFile(filepath.Join(root, "contracts", "local-rpc", "contract.json"))
	if err != nil {
		return generatedArtifacts{}, err
	}
	compactSchema, err := compactJSON(schema)
	if err != nil {
		return generatedArtifacts{}, err
	}
	if err := validateSources(catalog, compactSchema, localRPC); err != nil {
		return generatedArtifacts{}, err
	}
	compiledSchema, err := compileNativeSchema(schema)
	if err != nil {
		return generatedArtifacts{}, err
	}
	trustedFixture, err := compactFile(filepath.Join(root, "contracts", "card", "fixtures", "pomodoro-native.json"))
	if err != nil {
		return generatedArtifacts{}, err
	}
	if err := validateNativeSchemaDocument(compiledSchema, trustedFixture); err != nil {
		return generatedArtifacts{}, fmt.Errorf("validate trusted NativeCard fixture: %w", err)
	}

	contextJSON := []byte(`{"catalog":` + string(catalog) + `,"nativeSchema":` + string(compactSchema) + `,"localRpc":` + string(localRPC) + `}`)
	source := generatedHeader + "\npackage agent\n\nconst nativeContractContextJSON = " + strconv.Quote(string(contextJSON)) + "\n"
	formatted, err := format.Source([]byte(source))
	if err != nil {
		return generatedArtifacts{}, fmt.Errorf("format generated context: %w", err)
	}
	return generatedArtifacts{
		GoContext:         formatted,
		NativeSchema:      schema,
		DartCatalog:       dartCatalog,
		TypeScriptCatalog: typeScriptCatalog,
	}, nil
}

func compactJSON(content []byte) ([]byte, error) {
	var compact bytes.Buffer
	if err := json.Compact(&compact, content); err != nil {
		return nil, fmt.Errorf("compact generated JSON: %w", err)
	}
	return compact.Bytes(), nil
}

func validateCatalogDocument(schemaJSON, catalogJSON []byte) error {
	schemaDocument, err := jsonschema.UnmarshalJSON(bytes.NewReader(schemaJSON))
	if err != nil {
		return fmt.Errorf("decode NativeCard catalog schema: %w", err)
	}
	compiler := jsonschema.NewCompiler()
	compiler.DefaultDraft(jsonschema.Draft2020)
	if err := compiler.AddResource("native-card-catalog.schema.json", schemaDocument); err != nil {
		return fmt.Errorf("load NativeCard catalog schema: %w", err)
	}
	compiled, err := compiler.Compile("native-card-catalog.schema.json")
	if err != nil {
		return fmt.Errorf("compile NativeCard catalog schema: %w", err)
	}
	catalogDocument, err := jsonschema.UnmarshalJSON(bytes.NewReader(catalogJSON))
	if err != nil {
		return fmt.Errorf("decode NativeCard catalog: %w", err)
	}
	if err := compiled.Validate(catalogDocument); err != nil {
		return fmt.Errorf("validate NativeCard catalog schema: %w", err)
	}
	return nil
}

func compileNativeSchema(schemaJSON []byte) (*jsonschema.Schema, error) {
	schemaDocument, err := jsonschema.UnmarshalJSON(bytes.NewReader(schemaJSON))
	if err != nil {
		return nil, fmt.Errorf("decode generated NativeCard schema: %w", err)
	}
	compiler := jsonschema.NewCompiler()
	compiler.DefaultDraft(jsonschema.Draft2020)
	if err := compiler.AddResource("native-card.schema.json", schemaDocument); err != nil {
		return nil, fmt.Errorf("load generated NativeCard schema: %w", err)
	}
	compiled, err := compiler.Compile("native-card.schema.json")
	if err != nil {
		return nil, fmt.Errorf("compile generated NativeCard schema: %w", err)
	}
	return compiled, nil
}

func validateNativeSchemaDocument(compiled *jsonschema.Schema, documentJSON []byte) error {
	document, err := jsonschema.UnmarshalJSON(bytes.NewReader(documentJSON))
	if err != nil {
		return fmt.Errorf("decode NativeCard document: %w", err)
	}
	if err := compiled.Validate(document); err != nil {
		return fmt.Errorf("validate NativeCard document: %w", err)
	}
	return nil
}

func compactFile(path string) ([]byte, error) {
	content, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", path, err)
	}
	var compact bytes.Buffer
	if err := json.Compact(&compact, content); err != nil {
		return nil, fmt.Errorf("parse %s: %w", path, err)
	}
	return compact.Bytes(), nil
}

func validateSources(catalogJSON, schemaJSON, localRPCJSON []byte) error {
	var catalog catalogDocument
	if err := json.Unmarshal(catalogJSON, &catalog); err != nil {
		return fmt.Errorf("decode NativeCard catalog: %w", err)
	}
	var schema map[string]any
	if err := json.Unmarshal(schemaJSON, &schema); err != nil || schema["$id"] == nil {
		return fmt.Errorf("NativeCard schema is invalid")
	}
	var localRPC localRPCDocument
	if err := json.Unmarshal(localRPCJSON, &localRPC); err != nil {
		return fmt.Errorf("decode local RPC contract: %w", err)
	}
	if catalog.Version != 1 || localRPC.ContractVersion != 1 {
		return fmt.Errorf("only NativeCard catalog and local RPC version 1 are supported")
	}
	if len(catalog.Components) != 22 || len(catalog.Actions) != 8 || len(catalog.Expressions) != 14 {
		return fmt.Errorf("NativeCard catalog has unexpected semantic counts")
	}
	schemaComponents, schemaActions, schemaExpressions, err := schemaSemanticNames(schema)
	if err != nil {
		return err
	}
	if !sameStrings(sortedKeys(catalog.Components), schemaComponents) {
		return fmt.Errorf("NativeCard component names differ between catalog and schema")
	}
	if !sameStrings(sortedKeys(catalog.Actions), schemaActions) {
		return fmt.Errorf("NativeCard action names differ between catalog and schema")
	}
	if !sameStrings(sortedKeys(catalog.Expressions), schemaExpressions) {
		return fmt.Errorf("NativeCard expression names differ between catalog and schema")
	}
	for name, component := range catalog.Components {
		for propName, rule := range component.AllowedProps {
			if err := validateValueRule("component "+name+" prop "+propName, rule); err != nil {
				return err
			}
		}
		for _, required := range component.RequiredProps {
			if _, ok := component.AllowedProps[required]; !ok {
				return fmt.Errorf("component %s requires undeclared prop %s", name, required)
			}
		}
	}
	for name, action := range catalog.Actions {
		seen := make(map[string]bool, len(action.RequiredFields))
		hasValue := false
		for _, field := range action.RequiredFields {
			seen[field] = true
			hasValue = hasValue || field == "value"
		}
		for _, field := range action.OptionalFields {
			if seen[field] {
				return fmt.Errorf("action %s field %s is both required and optional", name, field)
			}
			hasValue = hasValue || field == "value"
		}
		hasValueRule := action.ValueRule != nil
		if hasValue != hasValueRule {
			return fmt.Errorf("action %s value field and valueRule must be declared together", name)
		}
		if action.ValueRule != nil {
			if err := validateValueRule("action "+name+" value", *action.ValueRule); err != nil {
				return err
			}
		}
	}
	for name, expression := range catalog.Expressions {
		if expression.MaxArgs != nil && *expression.MaxArgs < expression.MinArgs {
			return fmt.Errorf("expression %s maxArgs must be greater than or equal to minArgs", name)
		}
	}
	if err := validateCapabilityMethods(catalog.CapabilityMethods, localRPC.Methods); err != nil {
		return err
	}
	for _, behavior := range []string{"conditionalVisibility", "dynamicListMapping", "dateFormatting"} {
		if strings.TrimSpace(catalog.Unsupported[behavior]) == "" {
			return fmt.Errorf("unsupported behavior %s is undocumented", behavior)
		}
	}
	return nil
}

func validateValueRule(context string, rule valueRule) error {
	if rule.UniqueItems && rule.Type != "stringList" {
		return fmt.Errorf("%s uniqueItems requires stringList", context)
	}
	if rule.Minimum != nil && rule.Maximum != nil && *rule.Minimum > *rule.Maximum {
		return fmt.Errorf("%s minimum must be less than or equal to maximum", context)
	}
	if rule.Pattern != "" {
		if _, err := regexp.Compile(rule.Pattern); err != nil {
			return fmt.Errorf("%s pattern is invalid: %w", context, err)
		}
	}
	return nil
}

func schemaSemanticNames(schema map[string]any) ([]string, []string, []string, error) {
	definitions, ok := schema["$defs"].(map[string]any)
	if !ok {
		return nil, nil, nil, fmt.Errorf("NativeCard schema has no definitions")
	}
	node, ok := definitions["node"].(map[string]any)
	if !ok {
		return nil, nil, nil, fmt.Errorf("NativeCard schema has no node definition")
	}
	components, err := schemaBranchNames(node, "type")
	if err != nil {
		return nil, nil, nil, fmt.Errorf("NativeCard component schema: %w", err)
	}
	action, ok := definitions["action"].(map[string]any)
	if !ok {
		return nil, nil, nil, fmt.Errorf("NativeCard schema has no action definition")
	}
	actions, err := schemaBranchNames(action, "type")
	if err != nil {
		return nil, nil, nil, fmt.Errorf("NativeCard action schema: %w", err)
	}
	expression, ok := definitions["expression"].(map[string]any)
	if !ok {
		return nil, nil, nil, fmt.Errorf("NativeCard schema has no expression definition")
	}
	expressions, err := schemaBranchNames(expression, "op")
	if err != nil {
		return nil, nil, nil, fmt.Errorf("NativeCard expression schema: %w", err)
	}
	sort.Strings(components)
	sort.Strings(actions)
	sort.Strings(expressions)
	return components, actions, expressions, nil
}

func schemaBranchNames(schema map[string]any, discriminator string) ([]string, error) {
	items, ok := schema["oneOf"].([]any)
	if !ok {
		return nil, fmt.Errorf("oneOf is missing")
	}
	values := make([]string, 0, len(items))
	for _, rawBranch := range items {
		branch, ok := rawBranch.(map[string]any)
		if !ok {
			return nil, fmt.Errorf("branch is not an object")
		}
		properties, ok := branch["properties"].(map[string]any)
		if !ok {
			return nil, fmt.Errorf("branch properties are missing")
		}
		rule, ok := properties[discriminator].(map[string]any)
		if !ok {
			return nil, fmt.Errorf("branch discriminator %s is missing", discriminator)
		}
		value, ok := rule["const"].(string)
		if !ok || value == "" {
			return nil, fmt.Errorf("branch discriminator %s is invalid", discriminator)
		}
		values = append(values, value)
	}
	return values, nil
}

func sortedKeys[V any](values map[string]V) []string {
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}

func sameStrings(left, right []string) bool {
	if len(left) != len(right) {
		return false
	}
	for index := range left {
		if left[index] != right[index] {
			return false
		}
	}
	return true
}

func validateCapabilityMethods(methods map[string]capabilityMethodRule, localMethods []string) error {
	want := append([]string(nil), localMethods...)
	got := make([]string, 0, len(methods))
	for method, rule := range methods {
		got = append(got, method)
		capability := requiredCapability(method)
		if (rule.ManifestCapability == nil) != (capability == "") || (rule.ManifestCapability != nil && *rule.ManifestCapability != capability) {
			return fmt.Errorf("capability mapping for %s does not match Broker rules", method)
		}
		if !rule.NativeSupported && strings.TrimSpace(rule.UnsupportedReason) == "" {
			return fmt.Errorf("unsupported capability method %s has no reason", method)
		}
		if rule.NativeSupported && rule.ManifestCapability == nil {
			return fmt.Errorf("supported capability method %s has no manifest capability", method)
		}
	}
	sort.Strings(want)
	sort.Strings(got)
	if strings.Join(want, "\n") != strings.Join(got, "\n") {
		return fmt.Errorf("catalog capability methods do not match local RPC contract")
	}
	return nil
}

func requiredCapability(method string) string {
	if method == "runtime.getContext" {
		return ""
	}
	if strings.HasPrefix(method, "storage.") {
		return "storage"
	}
	if strings.HasPrefix(method, "window.") {
		return "window.manageSelf"
	}
	if strings.HasPrefix(method, "system.metrics.") {
		return "system.metrics.read"
	}
	return method
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
