package main

import (
	"encoding/json"
	"fmt"
	"sort"
)

func buildNativeSchema(catalog catalogDocument) ([]byte, error) {
	componentBranches := make([]any, 0, len(catalog.Components))
	for _, name := range sortedKeys(catalog.Components) {
		branch, err := componentSchema(
			name,
			catalog.Components[name],
			catalog.Limits["maxChildrenPerNode"],
			catalog.Limits["maxActionsPerEvent"],
		)
		if err != nil {
			return nil, err
		}
		componentBranches = append(componentBranches, branch)
	}
	actionBranches := make([]any, 0, len(catalog.Actions))
	for _, name := range sortedKeys(catalog.Actions) {
		branch, err := actionSchema(name, catalog.Actions[name], catalog.CapabilityMethods)
		if err != nil {
			return nil, err
		}
		actionBranches = append(actionBranches, branch)
	}
	expressionBranches := make([]any, 0, len(catalog.Expressions))
	for _, name := range sortedKeys(catalog.Expressions) {
		expressionBranches = append(expressionBranches, expressionSchema(name, catalog.Expressions[name]))
	}

	schema := map[string]any{
		"$schema":              "https://json-schema.org/draft/2020-12/schema",
		"$id":                  "https://agentcard.dev/contracts/card/native-card.schema.json",
		"$comment":             "Code generated by native-context-gen; DO NOT EDIT.",
		"title":                "AgentCard NativeCard v1",
		"type":                 "object",
		"additionalProperties": false,
		"required":             []string{"schemaVersion", "initialState", "root"},
		"properties": map[string]any{
			"schemaVersion": map[string]any{"const": catalog.Version},
			"initialState":  map[string]any{"type": "object"},
			"root":          map[string]any{"$ref": "#/$defs/node"},
		},
		"$defs": map[string]any{
			"node": map[string]any{"oneOf": componentBranches},
			"statePath": map[string]any{
				"type":      "string",
				"minLength": 1,
				"pattern":   `^[^.]+(?:\.[^.]+)*$`,
			},
			"expressionPath": map[string]any{
				"type":    "string",
				"pattern": `^state\.[^.]+(?:\.[^.]+)*$`,
			},
			"pathBinding": map[string]any{
				"type":                 "object",
				"additionalProperties": false,
				"required":             []string{"path"},
				"properties": map[string]any{
					"path": map[string]any{"$ref": "#/$defs/expressionPath"},
				},
			},
			"expressionBinding": map[string]any{
				"type":                 "object",
				"additionalProperties": false,
				"required":             []string{"expr"},
				"properties": map[string]any{
					"expr": map[string]any{"$ref": "#/$defs/expression"},
				},
			},
			"expression": map[string]any{"oneOf": expressionBranches},
			"timerConfiguration": map[string]any{
				"type":                 "object",
				"additionalProperties": false,
				"required":             []string{"intervalMs", "delta"},
				"properties": map[string]any{
					"intervalMs": map[string]any{"type": "integer", "minimum": 1},
					"delta":      map[string]any{"type": "number"},
					"stopAt":     map[string]any{"type": "number"},
				},
			},
			"action": map[string]any{"oneOf": actionBranches},
		},
	}
	content, err := json.MarshalIndent(schema, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("encode generated NativeCard schema: %w", err)
	}
	return append(content, '\n'), nil
}

func componentSchema(name string, rule componentRule, maxChildren, maxActions int) (map[string]any, error) {
	props := make(map[string]any, len(rule.AllowedProps))
	for propName, value := range rule.AllowedProps {
		propSchema, err := valueSchema(value)
		if err != nil {
			return nil, fmt.Errorf("component %s prop %s: %w", name, propName, err)
		}
		props[propName] = propSchema
	}
	propsSchema := map[string]any{
		"type":                 "object",
		"additionalProperties": false,
		"properties":           props,
	}
	if len(rule.RequiredProps) > 0 {
		propsSchema["required"] = append([]string(nil), rule.RequiredProps...)
	}
	events := make(map[string]any, len(rule.AllowedEvents))
	for _, event := range rule.AllowedEvents {
		events[event] = map[string]any{
			"type":     "array",
			"maxItems": maxActions,
			"items":    map[string]any{"$ref": "#/$defs/action"},
		}
	}
	eventsSchema := map[string]any{
		"type":                 "object",
		"additionalProperties": false,
		"properties":           events,
	}
	required := []string{"id", "type"}
	if len(rule.RequiredProps) > 0 {
		required = append(required, "props")
	}
	return map[string]any{
		"type":                 "object",
		"additionalProperties": false,
		"required":             required,
		"properties": map[string]any{
			"id": map[string]any{
				"type":      "string",
				"minLength": 1,
				"maxLength": 100,
			},
			"type":     map[string]any{"const": name},
			"props":    propsSchema,
			"events":   eventsSchema,
			"children": map[string]any{"type": "array", "maxItems": maxChildren, "items": map[string]any{"$ref": "#/$defs/node"}},
		},
	}, nil
}

func actionSchema(name string, rule actionRule, capabilities map[string]capabilityMethodRule) (map[string]any, error) {
	fields := append(append([]string(nil), rule.RequiredFields...), rule.OptionalFields...)
	properties := map[string]any{"type": map[string]any{"const": name}}
	for _, field := range fields {
		switch field {
		case "path":
			properties[field] = map[string]any{"$ref": "#/$defs/statePath"}
		case "value":
			if rule.ValueRule == nil {
				return nil, fmt.Errorf("action %s has value without valueRule", name)
			}
			value, err := valueSchema(*rule.ValueRule)
			if err != nil {
				return nil, fmt.Errorf("action %s value: %w", name, err)
			}
			properties[field] = value
		case "method":
			methods := make([]string, 0)
			for method, capability := range capabilities {
				if capability.NativeSupported {
					methods = append(methods, method)
				}
			}
			sort.Strings(methods)
			properties[field] = map[string]any{"type": "string", "enum": methods}
		case "params":
			properties[field] = map[string]any{"type": "object"}
		default:
			return nil, fmt.Errorf("action %s has unknown field %s", name, field)
		}
	}
	required := append([]string{"type"}, rule.RequiredFields...)
	return map[string]any{
		"type":                 "object",
		"additionalProperties": false,
		"required":             required,
		"properties":           properties,
	}, nil
}

func expressionSchema(name string, rule expressionRule) map[string]any {
	args := map[string]any{
		"type":     "array",
		"minItems": rule.MinArgs,
	}
	if rule.MaxArgs != nil {
		args["maxItems"] = *rule.MaxArgs
	}
	return map[string]any{
		"type":                 "object",
		"additionalProperties": false,
		"required":             []string{"op", "args"},
		"properties": map[string]any{
			"op":   map[string]any{"const": name},
			"args": args,
		},
	}
}

func valueSchema(rule valueRule) (map[string]any, error) {
	var literal map[string]any
	switch rule.Type {
	case "any":
		literal = map[string]any{}
	case "string", "number", "integer", "boolean", "object":
		literal = map[string]any{"type": rule.Type}
	case "stringList":
		literal = map[string]any{"type": "array", "items": map[string]any{"type": "string"}}
	case "numberList":
		literal = map[string]any{"type": "array", "items": map[string]any{"type": "number"}}
	case "timerConfiguration":
		literal = map[string]any{"$ref": "#/$defs/timerConfiguration"}
	default:
		return nil, fmt.Errorf("unknown value type %q", rule.Type)
	}
	if len(rule.Enum) > 0 {
		literal["enum"] = append([]string(nil), rule.Enum...)
	}
	if rule.Minimum != nil {
		literal["minimum"] = *rule.Minimum
	}
	if rule.Maximum != nil {
		literal["maximum"] = *rule.Maximum
	}
	if rule.MinLength != nil {
		literal["minLength"] = *rule.MinLength
	}
	if rule.Pattern != "" {
		literal["pattern"] = rule.Pattern
	}
	if rule.UniqueItems {
		literal["uniqueItems"] = true
	}
	if !rule.Binding {
		return literal, nil
	}
	return map[string]any{
		"anyOf": []any{
			literal,
			map[string]any{"$ref": "#/$defs/pathBinding"},
			map[string]any{"$ref": "#/$defs/expressionBinding"},
			map[string]any{"$ref": "#/$defs/expression"},
		},
	}, nil
}
